### PR TITLE
Get structured logging API ready for stabilization

### LINKED ISSUE #149: Structured Logging
One of the major points of discussion during the [log evaluation](https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-16-log/5185/50) was structured logging, specifically the `log` crate's relation to [`slog`](https://docs.rs/slog). In the review we ended up concluding that there's no reason to *not* add structured logging to the `log` crate and it'd be awesome to unify the slog/log ecosystems!

This issue is intended to serve as a tracking issue for concerns and ideas related to this. For example the specific APIs the `log` crate would have, how this would relate to `slog`, migration stories, etc.

### LINKED ISSUE #328: Tracking issue for kv_unstable (structured logging)
Tracking issue for the implementation of #296. See also #149 

- [x] Initial implementation (#324)
- [ ] Integration with frameworks and loggers:
  - [x] [`slog`](https://github.com/slog-rs/slog)
    - [x] Zero-allocation conversion between `slog::Value` and `log::kv::Value`. We should be able to do zero-allocation conversion from `log` to `slog`, but may need to allocate from `slog` to `log`.
  - [ ] [`tracing`](https://github.com/tokio-rs/tracing) (https://github.com/tokio-rs/tracing/issues/341)
    - [x] Zero-allocation conversion between `tracing::Value` and `log::kv::Value` in the `event!` macro (#339)
    - [x] Capture `std::error::Error`s as `Value`s
  - [ ] [`fern`](https://github.com/daboross/fern)
  - [ ] [`async-log`](https://github.com/rustasync/async-log)
  - [x] [`std-logger`](https://github.com/Thomasdezeeuw/std-logger) (https://github.com/Thomasdezeeuw/std-logger/pull/14)
    - [x] Some way to tell whether a `Source` has any key-value pairs (#329)
  - [ ] [`femme`](https://github.com/lrlna/femme)
  - [ ] [`env_logger`](https://github.com/sebasmagri/env_logger) (https://github.com/sebasmagri/env_logger/pull/137)
  - [x] [`antlog`](https://github.com/KodrAus/antlog) (an experimental wrapper to prove out requirements)
    - [x] A way to get specific values (#335)
    - [x] A way to coerce a value to a common type (#379)
  -  _Please suggest others to track!_
- [x] Explore macro support (#343)
  - [x] `log!("msg {}", interpolated, { key: value })` (#353) - We ended up having to revert this in `log`, but are experimenting externally
  - [x]  [`log_kv_macro`](https://docs.rs/kv-log-macro/1.0.6/kv_log_macro/)
  - [x] [`log_macros`](https://github.com/KodrAus/log_macros)
- [x] Integration with serialization frameworks:
  - [x] `serde`
    - [x] Conversion between `serde::Serialize` and `std::fmt::Debug` (https://github.com/rust-lang/rfcs/pull/2696). See [`serde_fmt`](https://github.com/KodrAus/serde_fmt).
  - [x] `sval` (#342)
- [ ] Micro benchmarks
- [ ] Documentation and examples
- [ ] Stabilization review
- [ ] Open questions
  - [ ] Should `Source::count` return a `Result<usize>` instead of a plain `usize`?

### LINKED ISSUE #357: Logging std::error::Errors
It would be really nice to have a specialized way of logging errors that implement `std::error::Error`. 

This would allow automatically capturing detailed information about an error, including the `Display` and `Debug` representations, and especially backtraces via the new `Error::backtrace`, which has an open PR.

The main purpose is to give the backend implementation the option to extract all desired information about an error and use it as appropriate for the output.

Not sure how this could fit into the current design, but I'd imagine an additional method on `Log` and a macro. 

```rust
trait Log {
  ...
  // The record serves the purpose of providing the location, and optionally an additional error message / metadata.
  // Question: Should the record be optional or required?
  fn error(&self, error: &dyn std::error::Error,  record: Option<&Record>);
}
```

Plus a macro. 

Naming for that macro would of course be somewhat awkward, considering `error!` exists.  Maybe `with_error!()`. Also there could be a variant of `error!` that allows specifying an error value.

One could of course ask if this is really necessary, since you could already write a custom macro or method that captures the required information as a `Record`. But I'd like to see a standardized way of doing this that gives the logger implementation the power to do what it wants, without forcing the user to make a decision here up-front.

### LINKED ISSUE #436: Stabilize kv_unstable
This is part of #328 

I think we've explored enough of this design space now and the API has been in use within the `tide` project for some time now with their own kv-capable logging macro.

By stabilizing just the backend (non-macro-supported) `kv` module we can let users depend on this with confidence so that projects like `tracing` can also utilize it.

# Migration path

The `kv` API will remain an opt-in optional API. All features that currently begin with `kv_unstable` will be changed to `kv`. We can keep these old unstable features around for a while if we need.

Any other changes that are needed should be included here.

# Steps

- [x] Public API review of the `kv` module
- [x] Stabilize [`sval`](https://github.com/sval-rs/sval)
- [x] Stabilize [`value-bag`](https://github.com/sval-rs/value-bag)
- [ ] Documentation and examples

cc @yoshuawuyts

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #149 
Closes #328 
Closes #357 
Closes #436 
Closes #584 

Based on the review in #584

The plan is to:

- [x] Deprecate `Value::capture_*` and `Value::downcast_*` methods. All deprecated APIs are gated under the old `kv_unstable` features and will be removed once we remove those old unstable features.
- [x] Fill in the documentation for structured logging support so people can actually use it.
- [x] Add some macro syntax for capturing attributes as debug or display instead of the default `ToValue` (`key:? = value`).
- [x] Only pull in `value-bag` as a dependency if either `serde` or `sval` is also needed. In cases where you just want basic structured logging, we should do it in a dependency-free way. This will just mean adding a simple `ValueInner` enum.

I'll cc once this is ready for review, to save a bit of notification noise.

Once this PR is complete, we should be able to stabilize structured logging support in the `log` crate.

### CODE REVIEW

**Comment by KodrAus** [comment]
We currently have `kv::source::Visitor` and `kv::value::Visit`. They're both visitor types (separate because they serve separate purposes), but should probably still be named consistently. @Thomasdezeeuw what do you think? Should we rename either `source::Visitor` or `value::Visit`? My preference would be to rename `value::Visit` to `value::Visitor`.

**Comment by Thomasdezeeuw** [comment]
> We currently have `kv::source::Visitor` and `kv::value::Visit`. They're both visitor types (separate because they serve separate purposes), but should probably still be named consistently. @Thomasdezeeuw what do you think? Should we rename either `source::Visitor` or `value::Visit`? My preference would be to rename `value::Visit` to `value::Visitor`.

I think `Visitor` is more common? So I would go with that.

I would understand possible confusing between the two traits, so maybe we need to rename one of the two? What about renaming `source::Visitor` to `KeyValuePairs` or just `KeyValues`, to indicate its a collection of key-value pairs?

**Comment by KodrAus** [comment]
> I would understand possible confusing between the two traits, so maybe we need to rename one of the two?

That's a fair point. Perhaps we could keep the names verb-y and use `VisitSource` and `VisitValue`?

**Comment by Thomasdezeeuw** [comment]
> That's a fair point. Perhaps we could keep the names verb-y and use `VisitSource` and `VisitValue`?

Sounds good :+1:

**Comment by KodrAus** [comment]
Ok, I think the last remaining thing here is macro syntax. We could adopt exactly `tracing`'s syntax of:

```
key = <modifier> arg
```

where `<modifier>` may be `?` for `fmt::Debug` or `%` for `fmt::Display`. I'm not a huge fan of leaning on sigils, or on prefixed modifiers here, because it leaves us almost no room for extensibility, but does have the benefit of being what's already there. I was thinking something like:

```
key = arg : <modifier>
```

where `<modifier`> may be blank for `fmt::Display`, `?` for `fmt::Debug`, or the literal text `serde` or `sval` for those respective libraries. In practice, it would look something like:

- `data`: captured using `ToValue`
- `data:`: captured using `fmt::Display`
- `data:?`: captured using `fmt::Debug`
- `data:serde`: captured using `serde::Serialize`
- `data:sval`: captured using `sval::Value`

We could use a simple lowering scheme so `data:?` lowered to `data:debug` and `data:` lowered to `data:display`, so it would be less easy to miss the presence of the `:`.

Another potential position could be on the key name:

```
key : <modifier> = arg
```

That would more easily let us expected `arg` to be a full expression in the future.

Any thoughts?

**Comment by Thomasdezeeuw** [comment]
> ```
> key = arg : <modifier>
> ```
> 
> where `<modifier`> may be blank for `fmt::Display`, `?` for `fmt::Debug`, or the literal text `serde` or `sval` for those respective libraries. In practice, it would look something like:

I like this, feels similar to `write!` (and `print!`, etc.) macros.

>     * `data:serde`: captured using `serde::Serialize`
> 
>     * `data:sval`: captured using `sval::Value`

Small thing is versioning, in case serde/sval ever publish a v2, how do we want to handle that? We can go `serdeV1` or `serde` or something else with a version in it, but if a v2 never comes it will just be annoying. So maybe `serde`/`sval` means v1, and `serde2`/`sval2` could v2?

> We could use a simple lowering scheme so `data:?` lowered to `data:debug` and `data:` lowered to `data:display`, so it would be less easy to miss the presence of the `:`.

Because we'll be copying the standard formatting found in the std lib, I don't think will become an issue.

> Another potential position could be on the key name:
> 
> ```
> key : <modifier> = arg
> ```
> 
> That would more easily let us expected `arg` to be a full expression in the future.

How would be limiting ourselves using the above `arg : <modifier>`? I suppose we won't be able to support full expressions?

**Comment by KodrAus** [comment]
> So maybe serde/sval means v1, and serde2/sval2 could v2?

That seems like a good scheme to me :+1: I spelled this out explicitly in `value-bag`, but it's not really meant to be user-facing. I think it's reasonable to make the "unversioned" ident refer to the current stable versions in `log`.

> How would be limiting ourselves using the above arg : <modifier>? I suppose we won't be able to support full expressions?

We'd just need to wrap full expressions in parenthesis or braces, because the `:` character can't appear directly after an expression in a macro rule.

**Comment by KodrAus** [comment]
This is quite a big change but I think it's ready for a review now. Some things to call out:

- The macro syntax I ended up with was `key:modifier = value`, so `key:? = value` for debug for instance. This was easier to implement and didn't require breaking any existing users.
- Should we make the `kv::source` and `kv::value` modules private now there's no types in them that aren't exported in the root `kv` module? I think we probably should.

File: src/kv/mod.rs [hunk 1]
```diff
@@ -11,16 +11,228 @@
...
+//! 
+//! The following capturing modifiers are supported:
+//! 
+//! - `:?` will capture the value using `Debug`.
+//! - `:debug` will capture the value using `Debug`.
+//! - `:%` will capture the value using `Display`.
+//! - `:display` will capture the value using `Display`.
+//! - `:error` will capture the value using `std::error::Error` (requires the `kv_unstable_error` feature).
+//! - `:sval` will capture the value using `sval::Value` (requires the `kv_unstable_sval` feature).
+//! - `:serde` will capture the value using `serde::Serialize` (requires the `kv_unstable_serde` feature).
```
Comment (Thomasdezeeuw) [inline src/kv/mod.rs:54]: I like this :+1:

File: src/kv/mod.rs [hunk 2]
```diff
@@ -11,16 +11,228 @@
...
+//! Individual values can be pulled from the source by their key:
+//!
+//! ```
+//! # fn main() -> Result<(), log::kv::Error> {
+//! use log::kv::{Source, Key, Value};
+//! # let record = log::Record::builder().key_values(&[("a", 1)]).build();
+//!
+//! // info!(a = 1; "Something of interest");
+//!
+//! let a: Value = record.key_values().get(Key::from("a")).unwrap();
```
Comment (Thomasdezeeuw) [inline src/kv/mod.rs:69]: Nit: maybe add `assert_eq!(a, Value::from(1));` to make it super clear?

File: src/kv/mod.rs [hunk 3]
```diff
@@ -11,16 +11,228 @@
...
+//! # Ok(())
+//! # }
+//! ```
+//!
+//! All key-values can also be enumerated using a [`VisitSource`]:
+//!
+//! ```
+//! # fn main() -> Result<(), log::kv::Error> {
+//! # let record = log::Record::builder().key_values(&[("a", 1), ("b", 2), ("c", 3)]).build();
```
Comment (Thomasdezeeuw) [inline src/kv/mod.rs:78]: Nit: want to move this above the `info!` statement so they stay in sync?

File: src/kv/mod.rs [hunk 4]
```diff
@@ -11,16 +11,228 @@
...
+//! ```
+//!
+//! To serialize a value to a format like JSON, you can also use either `serde` or `sval`:
+//!
+//! ```
+//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
+//! # #[cfg(feature = "serde")]
+//! # {
+//! # use log::kv::Key;
+//! # #[derive(serde::Serialize)] struct Data { a: i32, b: bool, c: &'static str }
```
Comment (Thomasdezeeuw) [inline src/kv/mod.rs:192]: I think we'll want to show this in the example so that people understand they need to implement/derive `serde::Serialize` for log (and `serde_json::to_string`)

File: src/kv/mod.rs [hunk 5]
```diff
@@ -11,16 +11,228 @@
...
+//! # }
+//! # Ok(())
+//! # }
+//! ```
+//!
+//! The choice of serialization framework depends on the needs of the consumer.
+//! If you're in a no-std environment, you can use `sval`. In other cases, you can use `serde`.
+//! Log producers and log consumers don't need to agree on the serialization framework.
+//! A value can be captured using its `serde::Serialize` implementation and still be serialized
+//! through `sval` without losing any structure.
```
Comment (Thomasdezeeuw) [inline src/kv/mod.rs:211]: Nit: maybe?
```suggestion
//! through `sval` without losing any structure or data.
```

File: src/kv/mod.rs [hunk 6]
```diff
@@ -11,16 +11,228 @@
...
+//!
+//! Values can also always be formatted using the standard `Debug` and `Display`
+//! traits:
+//!
+//! ```
+//! # use log::kv::Key;
+//! # #[derive(Debug)] struct Data { a: i32, b: bool, c: &'static str }
```
Comment (Thomasdezeeuw) [inline src/kv/mod.rs:218]: I would also show this in the example.

File: src/kv/source.rs [hunk 7]
```diff
@@ -1,25 +1,65 @@
...
 
 use crate::kv::{Error, Key, ToKey, ToValue, Value};
 use std::fmt;
 
-/// A source of key-value pairs.
+/// A source of key-values.
 ///
 /// The source may be a single pair, a set of pairs, or a filter over a set of pairs.
-/// Use the [`Visitor`](trait.Visitor.html) trait to inspect the structured data
+/// Use the [`VisitSource`](trait.VisitSource.html) trait to inspect the structured data
```
Comment (Thomasdezeeuw) [inline src/kv/source.rs:12]: Nit: don't think it's needed any more. But if we have it in other places, then let's leave it and do it some other time for all links.
```suggestion
/// Use the [`VisitSource`] trait to inspect the structured data
```

File: src/kv/source.rs [hunk 8]
```diff
@@ -34,14 +74,14 @@ pub trait Source {
...
+    /// Count the number of key-values that can be visited.
     ///
     /// # Implementation notes
     ///
-    /// A source that knows the number of key-value pairs upfront may provide a more
+    /// A source that knows the number of key-values upfront may provide a more
     /// efficient implementation.
     ///
-    /// A subsequent call to `visit` should yield the same number of key-value pairs
+    /// A subsequent call to `visit` should yield the same number of key-values
```
Comment (Thomasdezeeuw) [inline src/kv/source.rs:84]: Nit.
```suggestion
    /// A subsequent call to `visit` should yield the same number of key-values.
```

**Review by Thomasdezeeuw — APPROVED** [review]
I like it.

The only concern I have is that people find the modified on the key odd/unexpected, when coming from the `std::fmt` implementation. That might be worth calling out in the documentation.

File: Cargo.toml [hunk 9]
```diff
@@ -48,7 +48,7 @@ std = []
 
 # requires the latest stable
 # this will have a tighter MSRV before stabilization
-kv_unstable = ["value-bag"]
+kv_unstable = []
 kv_unstable_sval = ["kv_unstable", "value-bag/sval", "sval", "sval_ref"]
 kv_unstable_std = ["std", "kv_unstable", "value-bag/error"]
 kv_unstable_serde = ["kv_unstable_std", "value-bag/serde", "serde"]
```
[the remark this answers is not in the document]
Comment (KodrAus) [reply Cargo.toml:54]: It will, yes :+1: We technically don't need `value-bag` for capturing `std::error::Error`s, but do for `serde` or `sval`.

File: src/kv/source.rs (hunk 7 above)
Comment (KodrAus) [reply src/kv/source.rs:12]: Good call. I think I still need to do a pass over links and make sure they're all resolved correctly so will simplify them wherever possible.

File: src/__private_api.rs [hunk 10]
```diff
@@ -87,3 +84,42 @@ pub fn log<'a, K>(
...
+
+#[cfg(feature = "kv_unstable")]
+mod kv_support {
+    use super::*;
+
+    use crate::kv;
+
+    pub type Value<'a> = kv::Value<'a>;
+
+    pub fn capture_to_value<'a, V: kv::value::ToValue + ?Sized>(v: &'a &'a V) -> Value<'a> {
```
[the remark this answers is not in the document]
Comment (KodrAus) [reply src/__private_api.rs]: I left a comment in the source on why we do this. It's just so we can capture `T: ?Sized` while still erasing it behind a dyn Trait. Passing in the double reference in just helps the lifetimes work out.

**Comment by KodrAus** [comment]
The

```
err:error = err
```

way of capturing an error using the `std::error::Error` trait is maybe something we can improve on someday 🙂

**Comment by KodrAus** [comment]
I think the last thing remaining here is what to do about the `_unstable` suffix on our features. I was thinking making them just shims for the unsuffixed versions, but continuing to accept them so that we don't break every current user of the feature. What do you think @Thomasdezeeuw?

File: .github/workflows/main.yml [hunk 11]
```diff
@@ -44,10 +44,10 @@ jobs:
     - run: cargo test --verbose --all-features
     - run: cargo test --verbose --features serde
     - run: cargo test --verbose --features std
-    - run: cargo test --verbose --features kv_unstable
```
Comment (Thomasdezeeuw) [inline .github/workflows/main.yml:47]: We could start using [cargo-hack](https://crates.io/crates/cargo-hack) for this at some point (for another pr).

File: Cargo.toml [hunk 12]
```diff
@@ -46,25 +46,30 @@ release_max_level_trace = []
...
+kv = []
+kv_sval = ["kv", "value-bag/sval", "sval", "sval_ref"]
+kv_std = ["std", "kv", "value-bag/error"]
+kv_serde = ["kv_std", "value-bag/serde", "serde"]
+
+# Legacy: use `kv_*` instead
+kv_unstable = ["kv"]
+kv_unstable_sval = ["kv_sval"]
+kv_unstable_std = ["kv_std"]
+kv_unstable_serde = ["kv_serde"]
```
Comment (Thomasdezeeuw) [inline Cargo.toml:58]: To bad there is only `compile_error!`, not `compile_warn!` otherwise it would be nice to add that.

Comment (Thomasdezeeuw) [reply Cargo.toml:58]: Actually on second though... we're going to break a lot of (unstable) code already by removing the `as_serde` macros, do we just rip the bandaid in one go and break everything? Or should we add those macros back if [`kv_unstable`] is used (and mark them as `#[deprecated]`)?

**Review by Thomasdezeeuw — APPROVED** [review]
> I think the last thing remaining here is what to do about the `_unstable` suffix on our features. I was thinking making them just shims for the unsuffixed versions, but continuing to accept them so that we don't break every current user of the feature. What do you think @Thomasdezeeuw?

We can, but we a also have other breakages, e.g. the removal of the `as_{display,debug, etc.}` macros. Some of the API on `Value` has changes, which is also breaking.

So I'm wondering if we should keep some of the old API, if possible, if `kv_unstable` is used? Marking it all as deprecated show it at least generates warnings (I don't know if that is possible for features). Then e.g. 6 months after the stable release we can remove the `_unstable` feature and all it's related API? This would give people some time to migrate their code.

File: Cargo.toml (hunk 12 above)
Comment (KodrAus) [reply Cargo.toml:58]: I think this is a reasonable thing to do :+1:

Unfortunately you can’t mark them as deprecated but we can also re-export the renamed visitor traits under their old names when the old `_unstable` features are enabled.

**Comment by KodrAus** [comment]
How does this sound as a plan for stabilization:

1. Keep all old APIs when the `kv_unstable` feature is enabled, deprecating wherever possible.
2. Set a time period where we’ll remove the `kv_unstable` feature altogether and all those deprecated items. If we keep rough tabs on public code using the old features then we could get some idea of when would be a good time to do this.

The idea being new code and any maintained in that time period should move from the unstable to the stable API without much fuss, but there will be a point where the bandaid comes off completely. The only unfortunate part is we can’t deprecate old trait names so we don’t have a good way of making users of them aware things have changed.

**Comment by Thomasdezeeuw** [comment]
> How does this sound as a plan for stabilization:

Sounds good to me :+1:

**Comment by KodrAus** [comment]
In this latest round of changes I've restored the old APIs under their respective `*_unstable` feature flags and added support for shorthand capturing, so instead of having to write `info!(a = a; "")` you can write `info!(a; "")`.

**Comment by KodrAus** [comment]
Ok, I think this is ready for its last review now. Thank you so much for all the time you've invested in helping push this forwards so far @Thomasdezeeuw 🙏 We'd never have reached this point without you.

File: README.md [hunk 13]
```diff
@@ -116,7 +116,7 @@ pub fn shave_the_yak(yak: &mut Yak) {
                 break;
             }
             Err(err) => {
-                warn!(err:error = err; "Unable to locate a razor, retrying");
+                warn!(err:err; "Unable to locate a razor, retrying");
```
Comment (Thomasdezeeuw) [inline README.md:119]: Nit: maybe this makes the example a little confusing? Making it look like `:` is the separator for key-value pairs?

**Review by Thomasdezeeuw — APPROVED** [review]
Nice! Let's merge.

I'm gonna go over the API with https://github.com/Enselic/cargo-public-api/ see what, if any, difference there are

File: Cargo.toml [hunk 14]
```diff
@@ -46,25 +46,31 @@ release_max_level_trace = []
...
+kv_sval = ["kv", "value-bag/sval", "sval", "sval_ref"]
+kv_std = ["std", "kv", "value-bag/error"]
+kv_serde = ["kv_std", "value-bag/serde", "serde"]
+
+# Deprecated: use `kv_*` instead
+# These `*_unstable` features will be removed in a future release
+kv_unstable = ["kv"]
+kv_unstable_sval = ["kv_sval"]
+kv_unstable_std = ["kv_std"]
+kv_unstable_serde = ["kv_serde"]
```
Comment (Thomasdezeeuw) [inline Cargo.toml:59]: I think we need to enable these features.

```suggestion
kv_unstable = ["kv", "value-bag"]
kv_unstable_sval = ["kv_sval", "kv_unstable"]
kv_unstable_std = ["kv_std", "kv_unstable"]
kv_unstable_serde = ["kv_serde", "kv_unstable_std"]
```

This resolved most of the compilation errors for my crate, except for one. It can't find `log::kv::value::Visit`.

File: src/kv/value.rs [hunk 15]
```diff
@@ -765,13 +596,586 @@ where
...
+        note = "downcasting has been removed; log an issue at https://github.com/rust-lang/log/issues if this is something you rely on"
+    )]
+    pub fn downcast_ref<T: 'static>(&self) -> Option<&T> {
+        None
+    }
+}
+
+// NOTE: Deprecated; but aliases can't carry this attribute
+#[cfg(feature = "kv_unstable")]
+pub use VisitValue as Visitor;
```
Comment (Thomasdezeeuw) [inline src/kv/value.rs:1121]: Should this be visit?
```suggestion
pub use VisitValue as Visit;
```

File: README.md (hunk 13 above)
Comment (KodrAus) [reply README.md:119]: That's a good point. It could also look like it's trying to be a pattern binding 🤔 I'll try to clear it up.
